# Generated by Django 3.0.5 on 2020-04-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='upcreate',
            new_name='update',
        ),
    ]
